fix: ts error `error TS2304: Cannot find name 'TextDocument'.`
Forgot to import vscode's TextDocument interface for the `getArgs`.

https://github.com/valeryan/vscode-phpsab/actions/runs/18437461323/job/52532902543?pr=172